# Generated by Django 5.2.1 on 2025-05-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
    ]
