# Generated by Django 4.2.21 on 2025-05-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_formerpresident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormerPresident',
        ),
    ]
