# Generated by Django 4.2.21 on 2025-05-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_formerpresident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormerPresident',
        ),
    ]
