# Generated by Django 4.2.21 on 2025-06-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_formerpresident'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
    ]
