# Generated by Django 4.2.21 on 2025-06-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('3-2', '3-2'), ('4-1', '4-1'), ('4-2', '4-2')], max_length=5)),
                ('contact', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('media_publication', 'Media and Publication'), ('executive', 'Executive'), ('representative', 'Representative'), ('graphics_designer', 'Graphics Designer')], max_length=50)),
                ('anchoring_skills', models.TextField(blank=True, null=True, verbose_name='Anchoring Skills')),
                ('why_join', models.TextField(verbose_name='Why do you want to join this club?')),
                ('graphics_design_link', models.URLField(blank=True, null=True, verbose_name='Graphics Design Sample (Google Drive Link)')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
