# Generated by Django 4.2.21 on 2025-06-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitmentsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentsetting',
            options={'verbose_name': 'Recruitment Setting', 'verbose_name_plural': 'Recruitment Settings'},
        ),
    ]
