# Generated by Django 4.2.21 on 2025-06-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_recruitmentsetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Recruitment is Active')),
            ],
            options={
                'verbose_name': 'Recruitment Setting',
                'verbose_name_plural': 'Recruitment Settings',
            },
        ),
    ]
