# Generated by Django 4.2.21 on 2025-06-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_add_recruitment_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Currently Active')),
            ],
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.recruitmentdrive'),
        ),
    ]
