# Generated by Django 4.2.21 on 2025-05-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
