# Generated by Django 4.2.21 on 2025-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_delete_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('convenor', 'Convenor'), ('main_committee', 'Main Committee'), ('representative', 'Representative')], max_length=20)),
                ('sub_role', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_members/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which member appears')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
