# Generated by Django 4.2.21 on 2025-05-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='sub_role',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
    ]
