# Generated by Django 4.2.21 on 2025-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_rename_sub_role_teammember_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormerPresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tenure', models.CharField(help_text='e.g., 2020-2021', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='former_presidents/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which president appears')),
            ],
            options={
                'ordering': ['order', 'tenure', 'name'],
            },
        ),
    ]
