# Generated by Django 4.2.21 on 2025-05-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_formerpresident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormerPresident',
        ),
    ]
