# Generated by Django 4.2.21 on 2025-05-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_formerpresident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormerPresident',
        ),
    ]
