# Generated by Django 4.2.21 on 2025-06-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_formerpresident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormerPresident',
        ),
    ]
