# Generated by Django 4.2.21 on 2025-06-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contactmessage_replied_at_contactmessage_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
