# Generated by Django 4.2.21 on 2025-06-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_contactmessage_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='reply',
        ),
    ]
